function toNum(val) {
  if (val === null || val === undefined) return null;
  const cleaned = val.toString().replace(/,/g, "").trim();
  if (cleaned === "") return null;
  const n = parseFloat(cleaned);
  return Number.isNaN(n) ? null : n;
}

function niceTickStep(rawStep) {
  if (!Number.isFinite(rawStep) || rawStep <= 0) return 1;
  const magnitude = 10 ** Math.floor(Math.log10(rawStep));
  const normalized = rawStep / magnitude;
  const niceNormalized =
    normalized <= 1 ? 1 : normalized <= 2 ? 2 : normalized <= 5 ? 5 : 10;
  return niceNormalized * magnitude;
}

d3.csv(`PM1_Viewer.csv?ts=${Date.now()}`)
  .then(function (rows) {
    if (!rows || !rows.length) {
      console.error("CSV appears empty or failed to load.");
      return;
    }

    // Handles possible slight differences in column naming
    const cols = Object.keys(rows[0]);
    function findCol(label) {
      return cols.find((c) => c.trim() === label) || label;
    }

    const COL_YEAR = findCol("Year");
    const COL_VMT  = findCol("VMT (Million vehicle-miles traveled)");
    // This boundary follows the manually controlled PM1 cycle. Update it only
    // when MAPA adopts a new main year and the segment layer publishes its VMT.
    const latestActualYear = 2025;
    const availableYears = rows
      .filter(row => toNum(row[COL_VMT]) != null)
      .map(row => parseInt(row[COL_YEAR], 10))
      .filter(year => !Number.isNaN(year));
    const lastDisplayYear = Math.max(...availableYears);

    const yearsActual = [];   // solid line
    const vmtActual   = [];

    const yearsEst = [];      // dashed line
    const vmtEst   = [];

    rows.forEach((row) => {
      const rawYear = row[COL_YEAR];
      if (rawYear == null || rawYear.toString().trim() === "") return;

      const year = parseInt(rawYear, 10);
      if (Number.isNaN(year)) return;

      if (year < 2006 || year > lastDisplayYear) return;

      const vmtVal =
        toNum(row[COL_VMT]) ??
        toNum(row["VMT"]) ??
        null;

      if (vmtVal == null) return;

      // 1) Actual VMT through the manually controlled main year.
      if (year <= latestActualYear) {
        yearsActual.push(year);
        vmtActual.push(vmtVal);
      }

      // 2) Estimated VMT starts on the final actual point to avoid a gap and
      // continues through every projected year generated by the updater.
      if (year >= latestActualYear && year <= lastDisplayYear) {
        yearsEst.push(year);
        vmtEst.push(vmtVal);
      }
    });

    // Preserve useful scale context without returning to a zero baseline.
    // The preferred floor is 2,500 million VMT; the upper bound and rounded
    // intervals continue to expand automatically with future VMT values.
    const plottedVmt = [...vmtActual, ...vmtEst].filter(Number.isFinite);
    const minVmt = Math.min(...plottedVmt);
    const maxVmt = Math.max(...plottedVmt);
    const rawSpan = maxVmt - minVmt;
    const span = rawSpan > 0 ? rawSpan : Math.max(Math.abs(minVmt) * 0.1, 1);
    const preferredFloor = 2500;
    const dataFloor = Math.floor((minVmt - span * 0.1) / 500) * 500;
    const yAxisMin = Math.min(preferredFloor, dataFloor);
    const yTickStep = niceTickStep((maxVmt - yAxisMin) / 6);
    const yPadding = Math.max(span * 0.12, yTickStep * 0.5);
    const yAxisMax = Math.ceil((maxVmt + yPadding) / yTickStep) * yTickStep;

    // === Traces ===

    // Solid line: historical VMT through the current main year.
    const lineVMT = {
      x: yearsActual,
      y: vmtActual,
      type: "scatter",
      mode: "lines",
      name: "VMT (Millions)",
      line: {
        width: 4.5, // thicker line
        color: "rgb(0, 90, 95)",
      },
      hovertemplate: "Year %{x}<br>VMT: %{y:,.0f} million<extra></extra>",
    };

    // Dashed line shares the last actual point so there is no visual gap.
    const lineVMT_Est = {
      x: yearsEst,
      y: vmtEst,
      type: "scatter",
      mode: "lines",
      name: "Estimated VMT (Millions)",
      line: {
        width: 4.5,       // thicker dashed line
        color: "rgb(0, 90, 95)",
        dash: "dash",
      },
      hovertemplate: "Year %{x}<br>Estimated VMT: %{y:,.0f} million<extra></extra>",
    };

    // === Layout ===
    const layout = {
      title: "",
      xaxis: {
        tickmode: "linear",
        dtick: 2,
        showgrid: true,              // vertical grid lines
        gridcolor: "rgba(0,0,0,0.1)",
        zeroline: false,
        tickangle: -45,
        showline: true,
        linecolor: "rgba(60,60,60,0.75)",
        linewidth: 1.5,
      },
      yaxis: {
        title: "Million Vehicle Miles Traveled",
        range: [yAxisMin, yAxisMax],
        tick0: yAxisMin,
        dtick: yTickStep,
        tickformat: ",.0f",
        showgrid: true,              // horizontal grid lines
        gridcolor: "rgba(0,0,0,0.1)",
        zeroline: false,
        showline: false,
      },
      hovermode: "x unified",
      legend: {
        orientation: "h",
        x: 0.5,
        y: -0.2,
        xanchor: "center",
      },
      margin: { l: 80, r: 40, t: 20, b: 80 },
    };

    const config = {
      responsive: true,
      displayModeBar: true,
      displaylogo: false,
      modeBarButtonsToKeep: ["toImage"],
      toImageButtonOptions: {
        format: "png",
        filename: "regional-traffic-volumes",
        width: 1200,
        height: 600,
        scale: 1,
      },
    };

    Plotly.newPlot("chart", [lineVMT, lineVMT_Est], layout, config);
  })
  .catch(function (error) {
    console.error("Error loading CSV:", error);
  });
